site_name: DZ MkDocs
site_url: https://dz-mkdocs.github.io/
repo_url: https://github.com/dz-mkdocs

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  highlightjs: true
  language: es

nav:
  - Home: index.md
  - Microsoft Learn:
      - Check your knowledge: microsoft-learn/quiz.md

extra_css:
  - assets/css/quiz.css

extra_javascript:
  - assets/js/quiz.js

markdown_extensions:
  - toc:
      permalink: true
        #  - tables
        #  - admonition
        #  - footnotes
        #  - attr_list
        #  - md_in_html
        #  - def_list
        #  - pymdownx.superfences
        #  - pymdownx.details
        #  - pymdownx.highlight
        #  - pymdownx.tabbed

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - redirects

