site_name: DZ MkDocs
site_url: https://dz-mkdocs.github.io/
use_directory_urls: false

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Microsoft Learn:
      - Check your knowledge: microsoft-learn/quiz.md

extra_javascript:
  - assets/js/quiz.js

extra_css:
  - assets/css/quiz.css

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed

plugins:
  - search
  - minify
  - git-revision-date-localized
  - redirects

